using InvestmentTaxCalculator.Enumerations;
using InvestmentTaxCalculator.Model.Interfaces;
using InvestmentTaxCalculator.Model.UkTaxModel;
using InvestmentTaxCalculator.Model.UkTaxModel.Stocks;

using System.Text.Json.Serialization;

namespace InvestmentTaxCalculator.Model.TaxEvents;

[JsonPolymorphic()]
[JsonDerivedType(typeof(StockSplit), "stockSplit")]
[JsonDerivedType(typeof(ExcessReportableIncome), "eri")]
[JsonDerivedType(typeof(FundEqualisation), "fundEqualisation")]
[JsonDerivedType(typeof(TakeoverCorporateAction), "takeover")]
[JsonDerivedType(typeof(ReturnOfCapitalCorporateAction), "roc")]
[JsonDerivedType(typeof(SpinoffCorporateAction), "spinoff")]
public abstract record CorporateAction : TaxEvent
{
    [JsonIgnore]
    public DateOnly EffectiveDate => DateOnly.FromDateTime(Date);

    /// <summary>
    /// Ordered list of company tickers that this corporate action affects.
    /// Earlier tickers in the list must be processed before later tickers.
    /// </summary>
    public virtual IReadOnlyList<string> CompanyTickersInProcessingOrder => [AssetName];
    public abstract MatchAdjustment TradeMatching(ITradeTaxCalculation trade1, ITradeTaxCalculation trade2, MatchAdjustment matchAdjustment);
    public abstract void ChangeSection104(UkSection104 section104);
    public virtual string Reason => "";
    public override string ToSummaryString() => $"Corporate Action: {AssetName} ({Date.ToShortDateString()}) - {Reason}";
    public abstract AssetCategoryType AppliesToAssetCategoryType { get; }

    public virtual bool ElectTaxDeferral { get; init; } = false;

    [JsonIgnore]
    public CorporateActionTaxCalculation? CashDisposal { get; protected set; }

    /// <summary>
    /// List of disposals generated by this corporate action (e.g. cash-in-lieu).
    /// These are collected by the tax calculator during the calculation run.
    /// </summary>
    [JsonIgnore]
    public List<ITradeTaxCalculation> GeneratedDisposals { get; } = new();

    protected WrappedMoney ProcessCashResult(WrappedMoney cashAmount, WrappedMoney relevantCostBasis, decimal totalValue, decimal quantity, string actionName, UkSection104 section104)
    {
        WrappedMoney allowableCostUsed = UkTaxRules.CalculateAllowableCostForCash(cashAmount, relevantCostBasis, totalValue, ElectTaxDeferral);

        string calculationDetail;
        if (ElectTaxDeferral && UkTaxRules.IsSmallCash(cashAmount.Amount, totalValue))
        {
            WrappedMoney gainAmount = cashAmount - allowableCostUsed;
            calculationDetail = $"Small cash treatment (deferred) from {actionName}: \n" +
                                 $"\tCash Received: {cashAmount}\n" +
                                 $"\tRelevant Cost Basis: {relevantCostBasis}\n" +
                                 $"\tExcess Gain: {gainAmount} (taxable)\n" +
                                 $"\tAllowable Cost used to reduce gain: {allowableCostUsed}";

            // For small distribution deferrals:
            // If gainAmount > 0, we MUST report a disposal for the excess gain.
            // If gainAmount == 0, we have fully deferred the cash into the cost basis. No disposal is created.
            if (gainAmount.Amount > 0)
            {
                CreateCashDisposal(gainAmount, WrappedMoney.GetBaseCurrencyZero(), quantity, calculationDetail, section104);
            }
        }
        else
        {
            decimal cashProportion = totalValue > 0 ? cashAmount.Amount / totalValue : 0m;
            calculationDetail = $"Part-disposal cost calculation from {actionName}: \n" +
                                 $"\tCash: {cashAmount}\n" +
                                 $"\tTotal Value: {totalValue}\n" +
                                 $"\tCash Proportion: {cashAmount.Amount:F2} / {totalValue:F2} = {cashProportion:P2}\n" +
                                 $"\tAllowable Cost: {relevantCostBasis} * {cashProportion:P2} = {allowableCostUsed}";

            CreateCashDisposal(cashAmount, allowableCostUsed, quantity, calculationDetail, section104);
        }
        return allowableCostUsed;
    }

    protected void CreateCashDisposal(WrappedMoney proceeds, WrappedMoney allowableCost, decimal quantity, string info, UkSection104 section104)
    {
        ResidencyStatus residencyStatus = section104.ResidencyStatusRecord?.GetResidencyStatus(DateOnly.FromDateTime(Date))
            ?? ResidencyStatus.Resident;

        CashDisposal = new CorporateActionTaxCalculation(this, proceeds, allowableCost, residencyStatus, quantity, info);
        GeneratedDisposals.Add(CashDisposal);
    }
}
