using System.Globalization;

namespace InvestmentTaxCalculator.Model;

public record CountryCode(string ThreeDigitCode, string CountryName)
{
    public static readonly CountryCode UnknownRegion = new("ZZZ", "Unknown Region");

    public static CountryCode GetRegionByTwoDigitCode(string twoDigitCode)
    {
        try
        {
            RegionInfo region = new(twoDigitCode);
            string countryName = CountryCodes[region.ThreeLetterISORegionName];
            return new CountryCode(region.ThreeLetterISORegionName, countryName);
        }
        catch (KeyNotFoundException)
        {
            return UnknownRegion;
        }
        catch (ArgumentException)
        {
            return UnknownRegion;
        }
    }

    private static readonly Dictionary<string, string> CountryCodes = new()
    {
        { "AFG", "Afghanistan"},
        { "ALB", "Albania"},
        { "DZA", "Algeria"},
        { "ASM", "American Samoa"},
        { "AND", "Andorra"},
        { "AGO", "Angola"},
        { "AIA", "Anguilla"},
        { "ATG", "Antigua and Barbuda"},
        { "ARG", "Argentina"},
        { "ARM", "Armenia"},
        { "ABW", "Aruba"},
        { "AUS", "Australia"},
        { "AUT", "Austria"},
        { "AZE", "Azerbaijan"},
        { "BHS", "Bahamas"},
        { "BHR", "Bahrain"},
        { "BGD", "Bangladesh"},
        { "BRB", "Barbados"},
        { "BLR", "Belarus"},
        { "BEL", "Belgium"},
        { "BLZ", "Belize"},
        { "BEN", "Benin"},
        { "BMU", "Bermuda"},
        { "BTN", "Bhutan"},
        { "BOL", "Bolivia"},
        { "BES", "Bonaire or Saba or Sint Eustatius"},
        { "BIH", "Bosnia and Herzegovina"},
        { "BWA", "Botswana"},
        { "BRA", "Brazil"},
        { "VGB", "British Virgin Islands"},
        { "BRN", "Brunei Darussalam"},
        { "BGR", "Bulgaria"},
        { "BFA", "Burkino Faso"},
        { "MMR", "Burma (also known as Myanmar)"},
        { "BDI", "Burundi"},
        { "KHM", "Cambodia"},
        { "CMR", "Cameroon"},
        { "CAN", "Canada"},
        { "CPV", "Cape Verde"},
        { "CYM", "Cayman Islands"},
        { "CAF", "Central African Republic"},
        { "TCD", "Chad"},
        { "CHL", "Chile"},
        { "CHN", "China"},
        { "CXR", "Christmas Island"},
        { "COL", "Colombia"},
        { "COM", "Comoros"},
        { "COG", "Congo"},
        { "COK", "Cook Islands"},
        { "CRI", "Costa Rica"},
        { "CIV", "Côte d’Ivoire"},
        { "HRV", "Croatia"},
        { "CUB", "Cuba"},
        { "CUW", "Curaçao"},
        { "CYP", "Cyprus"},
        { "CZE", "Czech Republic"},
        { "COD", "Democratic Republic of the Congo (formerly Zaire)"},
        { "DNK", "Denmark"},
        { "DJI", "Djibouti"},
        { "DMA", "Dominica"},
        { "DOM", "Dominican Republic"},
        { "ECU", "Ecuador"},
        { "EGY", "Egypt"},
        { "SLV", "El Salvador"},
        { "GNQ", "Equatorial Guinea"},
        { "ERI", "Eritrea"},
        { "EST", "Estonia"},
        { "ETH", "Ethiopia"},
        { "FLK", "Falkland Islands"},
        { "FRO", "Faroe Islands"},
        { "FJI", "Fiji"},
        { "FIN", "Finland"},
        { "FRA", "France"},
        { "GUF", "French Guiana"},
        { "PYF", "French Polynesia"},
        { "GAB", "Gabon"},
        { "GMB", "Gambia"},
        { "GEO", "Georgia"},
        { "DEU", "Germany"},
        { "GHA", "Ghana"},
        { "GIB", "Gibraltar"},
        { "GRC", "Greece"},
        { "GRL", "Greenland"},
        { "GRD", "Grenada"},
        { "GLP", "Guadeloupe"},
        { "GUM", "Guam"},
        { "GTM", "Guatemala"},
        { "GGY", "Guernsey"},
        { "GIN", "Guinea"},
        { "GNB", "Guinea-Bissau"},
        { "GUY", "Guyana"},
        { "HTI", "Haiti"},
        { "HND", "Honduras"},
        { "HKG", "Hong Kong (SAR)"},
        { "HUN", "Hungary"},
        { "ISL", "Iceland"},
        { "IND", "India"},
        { "IDN", "Indonesia"},
        { "IRN", "Iran"},
        { "IRQ", "Iraq"},
        { "IRL", "Ireland (Republic of)"},
        { "IMN", "Isle of Man"},
        { "ISR", "Israel"},
        { "ITA", "Italy"},
        { "JAM", "Jamaica"},
        { "JPN", "Japan"},
        { "JEY", "Jersey"},
        { "JOR", "Jordan"},
        { "KAZ", "Kazakhstan"},
        { "KEN", "Kenya"},
        { "KIR", "Kiribati"},
        { "XKX", "Kosovo"},
        { "KWT", "Kuwait"},
        { "KGZ", "Kyrgyzstan"},
        { "LAO", "Laos"},
        { "LVA", "Latvia"},
        { "LBN", "Lebanon"},
        { "LSO", "Lesotho"},
        { "LBR", "Liberia"},
        { "LBY", "Libya"},
        { "LIE", "Liechtenstein"},
        { "LTU", "Lithuania"},
        { "LUX", "Luxembourg"},
        { "MAC", "Macao (SAR)"},
        { "MKD", "Macedonia (FYR)"},
        { "MDG", "Madagascar"},
        { "MWI", "Malawi"},
        { "MYS", "Malaysia"},
        { "MDV", "Maldives"},
        { "MLI", "Mali"},
        { "MLT", "Malta"},
        { "MHL", "Marshall Islands"},
        { "MTQ", "Martinique"},
        { "MRT", "Mauritania"},
        { "MUS", "Mauritius"},
        { "MYT", "Mayotte"},
        { "MEX", "Mexico"},
        { "FSM", "Micronesia"},
        { "MDA", "Moldova"},
        { "MCO", "Monaco"},
        { "MNG", "Mongolia"},
        { "MNE", "Montenegro"},
        { "MSR", "Montserrat"},
        { "MAR", "Morocco"},
        { "MOZ", "Mozambique"},
        { "NAM", "Namibia"},
        { "NRU", "Nauru"},
        { "NPL", "Nepal"},
        { "NLD", "Netherlands"},
        { "NCL", "New Caledonia"},
        { "NZL", "New Zealand"},
        { "NIC", "Nicaragua"},
        { "NER", "Niger"},
        { "NGA", "Nigeria"},
        { "NIU", "Niue"},
        { "NFK", "Norfolk Island"},
        { "PRK", "North Korea"},
        { "MNP", "Northern Mariana Islands"},
        { "NOR", "Norway"},
        { "OMN", "Oman"},
        { "PAK", "Pakistan"},
        { "PLW", "Palau"},
        { "PAN", "Panama"},
        { "PNG", "Papua New Guinea"},
        { "PRY", "Paraguay"},
        { "PER", "Peru"},
        { "PHL", "Philippines"},
        { "PCN", "Pitcairn Island"},
        { "POL", "Poland"},
        { "PRT", "Portugal"},
        { "PRI", "Puerto Rico"},
        { "QAT", "Qatar"},
        { "REU", "Reunion"},
        { "ROU", "Romania"},
        { "RUS", "Russian Federation"},
        { "RWA", "Rwanda"},
        { "WSM", "Samoa"},
        { "SMR", "San Marino"},
        { "STP", "Sao Tome and Principe"},
        { "SAU", "Saudi Arabia"},
        { "SEN", "Senegal"},
        { "SRB", "Serbia and Montenegro"},
        { "SYC", "Seychelles"},
        { "SLE", "Sierra Leone"},
        { "SGP", "Singapore"},
        { "SXM", "Sint Maarten (Dutch part)"},
        { "SVK", "Slovak Republic"},
        { "SVN", "Slovenia"},
        { "SLB", "Solomon Islands"},
        { "SOM", "Somalia"},
        { "ZAF", "South Africa"},
        { "KOR", "South Korea"},
        { "SSD", "South Sudan"},
        { "ESP", "Spain"},
        { "LKA", "Sri Lanka"},
        { "SHN", "St Helena and Dependencies"},
        { "KNA", "St Kitts and Nevis"},
        { "LCA", "St Lucia"},
        { "SPM", "St Pierre and Miquelon"},
        { "VCT", "St Vincent and the Grenadines"},
        { "SDN", "Sudan"},
        { "SUR", "Suriname"},
        { "SJM", "Svalbard and Jan Mayen Islands"},
        { "SWZ", "Swaziland"},
        { "SWE", "Sweden"},
        { "CHE", "Switzerland"},
        { "SYR", "Syria"},
        { "TWN", "Taiwan"},
        { "TJK", "Tajikistan"},
        { "TZA", "Tanzania"},
        { "THA", "Thailand"},
        { "TLS", "Timor-Leste"},
        { "TGO", "Togo"},
        { "TKL", "Tokelau"},
        { "TON", "Tonga"},
        { "TTO", "Trinidad and Tobago"},
        { "TUN", "Tunisia"},
        { "TUR", "Turkey"},
        { "TKM", "Turkmenistan"},
        { "TCA", "Turks and Caicos Islands"},
        { "TUV", "Tuvalu"},
        { "UGA", "Uganda"},
        { "UKR", "Ukraine"},
        { "ARE", "United Arab Emirates"},
        { "GBR", "United Kingdom"},
        { "USA", "United States of America"},
        { "VIR", "United States Virgin Islands"},
        { "URY", "Uruguay"},
        { "UZB", "Uzbekistan"},
        { "VUT", "Vanuatu"},
        { "VAT", "Vatican"},
        { "VEN", "Venezuela"},
        { "VNM", "Vietnam"},
        { "WLF", "Wallis and Futuna Islands"},
        { "YEM", "Yemen"},
        { "ZMB", "Zambia"},
        { "ZWE", "Zimbabwe"},
    };
}